### ISSUE TITLE
Issue Set 1 :), pm if any questions!

### ISSUE THREAD

**Issue by romeo728** [DZ-0/Project-Avius-#1]
A. Controls/Key Binding (exclude binding for grapple, sword attacks, specials)

B.Collisions rework

C. Movement (values are up to interpretation for now)
-Run: running animation with decent movement speed
-Super Run: sprint animation with double or more than the original run values
-Jump: Vertical ascend 
-Run to Jump: slightly adds to Jump height and mid-air horizontal travel.
-Super run to Jump: doubles "run to Jump" values.
-Walljump: when up against a wall, repeatedly pressing space allows the player to ascend up that wall. Jump values can be translated to the wall jump (any "run to wall jump" will effect character placement on said wall, but not the wall jump values). If the player stops pressing "space" the character will fall.

-Air Dash: When the player is in mid-air, double tapping "A" or "D" can have the character dash.

-Grapple: N/A

**Comment by EverlessDrop41** [comment]
Seperated this issue in seperate issues

Controls: #2 

Collisions: #3 

Movement: #4
