### ISSUE TITLE
Movement Continued

### ISSUE THREAD

**Issue by romeo728** [DZ-0/Project-Avius-#6]
A.	Slide: The slide is executed when the player presses down (S)during sprint. This mechanic is not effected by any other variable, it only covers an particular distance every time used.  Later on in-game that distance will be increased with a movement buffs. The slide can only activated when the player is grounded. Slide cancels whenever the player collides with an object. 
B.	Wall Jump Contin.: Avius should be able to wall jump off of platforms as well
C.	Jump Contin: How long you hold the jump button determines height, for instance just taping  "space" will only push the character up a short vertical distance, while holding it would achieve its max (the max value is what you guys already have the jump set to).  This makes manuvering for the player much easier during platforming sections, since they can not only take the sprint into account but a short jump as well. They would use this ín scenarios where the roof is spiked and jumping at normal height would result in a death.

**Comment by EverlessDrop41** [comment]
Took these issues and put them in #4
